import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI-Driven Smart Finance Platform",
  description:
    "J26-SE-325 — liquidity-aware forecasting, portfolio optimization, fraud detection, blockchain auditability and explainable agentic assistance.",
};

// LayoutProps<"/"> is generated by `next dev` / `next build` / `next typegen` in Next 16 —
// this is the convention create-next-app scaffolds, kept rather than hand-writing props.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
